<?php
/**
 * Appearance → Icons screen.
 *
 * @package InfiniteIcons
 */

declare( strict_types = 1 );

namespace InfiniteIcons\Settings;

use InfiniteIcons\Packs\IndexClient;

defined( 'ABSPATH' ) || exit;

/**
 * Registers the settings screen and loads its React app.
 *
 * @since 1.0.0
 */
final class AdminPage {

	/**
	 * Menu slug.
	 *
	 * @since 1.0.0
	 * @var string
	 */
	const SLUG = 'infinite-icons';

	/**
	 * Script and style handle.
	 *
	 * @since 1.0.0
	 * @var string
	 */
	const HANDLE = 'infinite-icons-settings';

	/**
	 * Hook suffix of the settings page, once registered.
	 *
	 * @since 1.0.0
	 * @var string
	 */
	private $hook = '';

	/**
	 * Registers hooks.
	 *
	 * @since 1.0.0
	 *
	 * @return void
	 */
	public function register(): void {
		add_action( 'admin_menu', array( $this, 'add_menu' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue' ) );
		add_filter( 'plugin_action_links_' . plugin_basename( INFINITE_ICONS_FILE ), array( $this, 'action_links' ) );
	}

	/**
	 * Adds the Appearance → Icons page.
	 *
	 * @since 1.0.0
	 *
	 * @return void
	 */
	public function add_menu(): void {
		$hook       = add_theme_page(
			__( 'Icons', 'infinite-icons' ),
			__( 'Icons', 'infinite-icons' ),
			'manage_options',
			self::SLUG,
			array( $this, 'render' )
		);
		$this->hook = is_string( $hook ) ? $hook : '';
	}

	/**
	 * Adds a Settings link on the Plugins screen.
	 *
	 * @since 1.0.0
	 *
	 * @param array<int, string> $links Existing links.
	 * @return array<int, string>
	 */
	public function action_links( $links ): array {
		$settings = sprintf(
			'<a href="%s">%s</a>',
			esc_url( admin_url( 'themes.php?page=' . self::SLUG ) ),
			esc_html__( 'Settings', 'infinite-icons' )
		);
		array_unshift( $links, $settings );
		return $links;
	}

	/**
	 * Prints the mount point.
	 *
	 * @since 1.0.0
	 *
	 * @return void
	 */
	public function render(): void {
		printf(
			'<div class="wrap"><h1>%s</h1><div id="infinite-icons-root"><p>%s</p></div></div>',
			esc_html__( 'Icons', 'infinite-icons' ),
			esc_html__( 'Loading…', 'infinite-icons' )
		);
	}

	/**
	 * Loads the app on its own screen.
	 *
	 * @since 1.0.0
	 *
	 * @param string $hook_suffix Current admin page.
	 * @return void
	 */
	public function enqueue( $hook_suffix ): void {
		if ( '' === $this->hook || $hook_suffix !== $this->hook ) {
			return;
		}

		$asset_file = INFINITE_ICONS_DIR . 'build/settings.asset.php';
		if ( ! is_readable( $asset_file ) ) {
			add_action( 'admin_notices', array( $this, 'build_missing_notice' ) );
			return;
		}

		// Generated by @wordpress/scripts at build time and shipped in the
		// plugin; the path is a constant, not user input.
		// phpcs:ignore WordPressVIPMinimum.Files.IncludingFile.UsingVariable -- Build artefact inside the plugin.
		$asset = require $asset_file;

		wp_enqueue_script(
			self::HANDLE,
			INFINITE_ICONS_URL . 'build/settings.js',
			$asset['dependencies'] ?? array(),
			$asset['version'] ?? INFINITE_ICONS_VERSION,
			true
		);
		// wp-scripts names a stylesheet imported from the entry point
		// "style-<entry>.css", and emits an -rtl.css beside it.
		wp_enqueue_style(
			self::HANDLE,
			INFINITE_ICONS_URL . 'build/style-settings.css',
			array( 'wp-components' ),
			$asset['version'] ?? INFINITE_ICONS_VERSION
		);
		wp_style_add_data( self::HANDLE, 'rtl', 'replace' );
		wp_set_script_translations( self::HANDLE, 'infinite-icons' );

		wp_add_inline_script(
			self::HANDLE,
			'window.infiniteIconsSettings = ' . wp_json_encode(
				array(
					'root'      => esc_url_raw( rest_url( 'infinite-icons/v1' ) ),
					'nonce'     => wp_create_nonce( 'wp_rest' ),
					'version'   => INFINITE_ICONS_VERSION,
					'indexHost' => (string) wp_parse_url( ( new IndexClient() )->url(), PHP_URL_HOST ),
					'docsUrl'   => 'https://github.com/CoderAbhinav/infinite-icons',
				)
			) . ';',
			'before'
		);
	}

	/**
	 * Warns when the built assets are missing.
	 *
	 * @since 1.0.0
	 *
	 * @return void
	 */
	public function build_missing_notice(): void {
		printf(
			'<div class="notice notice-error"><p>%s</p></div>',
			esc_html__( 'Infinite Icons: the admin assets have not been built. Run "npm install && npm run build" in the plugin directory.', 'infinite-icons' )
		);
	}
}
